name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build installer
        run: ./gradlew jpackage --stacktrace

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: angels-care-windows-installer
          if-no-files-found: error
          path: app/build/jpackage/*.exe
